# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  docker: circleci/docker@2.4.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test:
    # These next lines define a Docker executor: https://circleci.com/docs/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # Be sure to update the Docker image tag below to openjdk version of your application.
    # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/openjdk
    docker:
      - image: cimg/openjdk:17.0.9
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      # Use mvn clean and package as the standard maven build phase
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - persist_to_workspace:
          root: ~/project
          paths:
            - "."
      # Then run your tests!
      # - run:
      #     name: Test
      #     command: mvn test
  tag-docker-images:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Install Kustomize
          command: |
            URL="https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"
            curl -s $URL | bash
            sudo chmod +x ./kustomize
            sudo mv ./kustomize /usr/local/bin
      - add_ssh_keys:
          fingerprints:
            - "84:65:e7:d0:75:63:07:cb:08:7c:19:c2:2d:74:59:ba"
      - run: 
          name: "establish authenticity of github"
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
      - run:
          name: Clone manifests github repo
          working_directory: ~/
          command: |
            URL="git@github.com:Disease-Prediction-AI/medical-disease-detection-manifests.git"
            git clone $URL manifests
      - run:
          name: Modify image tags
          working_directory: ~/manifests
          command: |
            kustomize edit set image $DOCKER_USERNAME/$APP_NAME-service=$DOCKER_USERNAME/$APP_NAME-service:$CIRCLE_SHA1
      - run:
          name: Commit & Push to manifests Github repo
          working_directory: ~/manifests
          command: |
            git config user.email "$GITHUB_EMAIL"
            git config user.name "CircleCI User"
            git add kustomization.yml
            git commit -am "Modified docker image tags [skip ci]"
            git push origin main

# Invoke jobs via workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-push-docker-image: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test:
          name: "build maven project"
      - docker/publish:
          name: "Push backend service image"
          image: $DOCKER_USERNAME/$APP_NAME-service
          tag: $CIRCLE_SHA1,latest
          docker-password: DOCKER_PASSWORD
          docker-username: DOCKER_USERNAME
          attach-at: ./
          requires:
            - "build maven project"
          
      - tag-docker-images:
          requires:
            - "Push backend service image"

